### ISSUE TITLE
Race condition on Prisma generated client

### ISSUE THREAD

**Issue by ryanpag3** [ludicroushq/prisma-integration-test-example#2]
Hey there! I stumbled upon your article when attempting to solve a similar problem. I have about 30 test suites and over 200 integration tests and when I run on an 8 core CPU I sometimes will see a race condition where the generated prisma client doesn't exist due to the `db push` that the mock prisma client uses. Have you solved this in your environment? 

Thanks in advance.

`no such file or directory, open '/actions-runner/_work/guac-bot/guac-bot/bot/node_modules/.prisma/client/index.js'`

**Comment by nahtnam** [comment]
Hey! Unfortunately I don't have that many tests so I've never come across this issue. However, it's super weird that you're getting a `no such file or directory` error. Can you try adding `--skip-generate` to the DB push command? https://github.com/ludicroushq/prisma-integration-test-example/blob/master/prisma/__mocks__/index.ts#L26 Maybe that will fix it

**Comment by ryanpag3** [comment]
hey sorry for the delay but `--skip-generate` was huge! reduced the overall test duration by about 60% as well. Thanks!
